### ISSUE TITLE
State of this project?

### ISSUE THREAD

**Issue by leugengroot** [uliwitness/TADSWorkbench#1]
Seeing that the last commits to this projects are more than four years ago I presume, that you abandoned this project. Can you say a few words about the last state of this project? Was it written from scratch or some kind of rewrite of the windows TADS3 workbench?

**Comment by FuzzyBoots** [comment]
I too am interested in knowing. :-/ I don't think I ever got around to getting this one to compile, since I was able to run the Windows one via Wine.

**Comment by leugengroot** [comment]
same here, I do most of the TADS3 stuff with atom and compiling on the console. But a real IDE would be very nice ...

**Comment by uliwitness** [comment]
The TADS Workbench app itself (i.e. the text editor and t3make file editor) was written from scratch, but it embedded the Unix TADS 3 compiler toolchain that existed at the time.

Since that toolchain was discontinued, I made an attempt at updating it to be based on FrobTADS instead (I think? Whatever command line compiler for Unix/Mac existed at the time), but I didn't have the time to finish the needed rewrites.
